name: LegendGeom

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
  release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    name: Test LegendGeom with Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for tests
      env:
          SYSTEM_VERSION_COMPAT: 0
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install --upgrade .[test]
    - name: Run unit tests
      run: |
        pytest

  test-coverage:
    name: Calculate and upload test coverage
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Generate Report
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade .[test]
          pytest --cov=pylegendgeom --cov-report=xml
      - name: Upload Coverage to codecov.io
        uses: codecov/codecov-action@v4

  build-docs:
    name: Build documentation
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup build environment
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade .[docs]
      - name: Build docs for current ref
        run: |
          cd docs
          make clean
          make
